mvn install:install-file -Dfile=D:\jars\nsms.jar -DgroupId=com.newgen.nsms -DartifactId=nsms -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=D:\jars\NIPLJ.jar -DgroupId=com.newgen.NIPLJ -DartifactId=NIPLJ -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=D:\jars\jtssessionbean.jar -DgroupId=com.newgen.jtssessionbean -DartifactId=jtssessionbean -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=D:\jars\jdts.jar -DgroupId=com.newgen.jdts -DartifactId=jdts -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=D:\jars\ISPack.jar -DgroupId=com.newgen.ispack -DartifactId=ispack -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=D:\jars\ejbclient.jar -DgroupId=com.newgen.ejbclient -DartifactId=ejbclient -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=D:\jars\dmsapi.jar -DgroupId=com.newgen.dmsapi -DartifactId=dmsapi -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=D:\jars\azure.jar -DgroupId=com.newgen.azure -DartifactId=azure -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=D:\jars\azure-storage-5.0.0.jar -DgroupId=com.newgen.azurestorage -DartifactId=azurestorage -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=D:\jars\aws-java-sdk-1.11.40.jar -DgroupId=com.newgen.awssdk -DartifactId=awssdk -Dversion=1.0 -Dpackaging=jar
